# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:ddMMyyyy)$(Rev:.r)
variables:
  var1: value1

stages:
- stage: testing
  displayName: testing stage
  variables:
    testing_var: "hello"
  jobs:
  - job: "SayingHello"
    container: "mattgomes28/wavytune:latest"
    steps:
    - script: |
        python3 -c "print('hello from job')"
        pip3 install colorama