# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:ddMMyyyy)$(Rev:.r)
variables:
  var1: value1

stages:
- stage: compilationx86_64
  displayName: Compiling For x86_64
  variables:
    BUILD_TYPE: "DEBUG"
  jobs:
  - job: "compile"
    container: "mattgomes28/wavytune:comp"
    steps:
    - script: mkdir build && cd build
      displayName: "Create Build Dir"
    - script: conan install --build=missing ..
      displayName: "Install Dependencies"
    - script: |
        cd build
        cmake -DCMAKE_MODULE_PATH:FILE_PATH="$(pwd)"
      displayName: "Generating CMake"
    - script: |
        cd build
        cmake --build . 
      displayName: "Building"