# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:ddMMyyyy)$(Rev:.r)
variables:
  var1: value1

stages:
- stage: compilationx86_64
  displayName: Compiling For x86_64
  variables:
    BUILD_TYPE: "DEBUG"
  jobs:
  - job: "compile"
    container: "mattgomes28/wavytune:compx86_64"
    steps:
    - script: |
        mkdir build && cd build
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan install --build=missing ..
        cmake -DCMAKE_MODULE_PATH:FILE_PATH="$(pwd)"
        cmake --build .
      displayName: "Building in build/"